[package]
name = "ofs_support"
version = "0.1.0"
authors = ["Christopher Miller <admin@mctherealm.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
