edition = "2018"
format_code_in_doc_comments = true
match_block_trailing_comma = true
imports_granularity = "Module"
newline_style = "Unix"
reorder_impl_items = true
group_imports = "StdExternalCrate"
tab_spaces = 2
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
max_width = 120
